[package]
name = "rvfish_bot"
version = "0.4.0"
authors = ["Andriy Chyvonomys <sima.rv@gmail.com>"]

[dependencies]
iron = "*"
persistent = "*"
bodyparser = "*"
router = "*"
hyper = "*"
hyper-native-tls = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
log = "*"
env_logger = "*"
