[package]
name = "rvfish_bot"
version = "0.4.6"
authors = ["Andriy Chyvonomys <sima.rv@gmail.com>"]

[dependencies]
iron = "*"
persistent = "*"
bodyparser = "*"
router = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
log = "0.4"
env_logger = "0.6"
lazy_static = "*"
