[package]
name = "rvfish_bot"
version = "0.4.4"
authors = ["Andriy Chyvonomys <sima.rv@gmail.com>"]

[dependencies]
iron = "*"
persistent = "*"
bodyparser = "*"
router = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
log = "*"
env_logger = "*"
lazy_static = "*"
